"""
TerraVision IBVAP — Virtual Fence Engine

Implements zone intrusion, tripwire crossing, directional tripwire,
and dwell-zone detection. All logic is purely geometric — no extra
AI models needed. Runs on top of existing YOLO + ByteTrack detections.
"""

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

from shapely.geometry import Point, Polygon, LineString


class ZoneType(str, Enum):
    INTRUSION = "intrusion"
    TRIPWIRE = "tripwire"
    DIRECTIONAL_TRIPWIRE = "directional_tripwire"
    DWELL = "dwell"


class AlertSeverity(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass
class FenceZone:
    """Definition of a virtual fence zone."""

    id: str
    name: str
    camera_id: str
    zone_type: ZoneType
    severity: AlertSeverity = AlertSeverity.HIGH
    enabled: bool = True

    # For INTRUSION and DWELL zones — polygon vertices [[x,y], ...]
    polygon_points: list[list[int]] = field(default_factory=list)

    # For TRIPWIRE — line endpoints [[x1,y1], [x2,y2]]
    line_points: list[list[int]] = field(default_factory=list)

    # For DIRECTIONAL_TRIPWIRE — allowed direction ("left_to_right", "right_to_left")
    direction: Optional[str] = None

    # For DWELL zone — time threshold in seconds
    dwell_threshold: float = 10.0

    # Color for rendering on dashboard (hex)
    color: str = "#ef4444"

    def get_polygon(self) -> Optional[Polygon]:
        """Build a Shapely Polygon from the stored points."""
        if len(self.polygon_points) >= 3:
            return Polygon(self.polygon_points)
        return None

    def get_line(self) -> Optional[LineString]:
        """Build a Shapely LineString from the stored line points."""
        if len(self.line_points) >= 2:
            return LineString(self.line_points)
        return None


@dataclass
class FenceAlert:
    """An alert generated by the virtual fence engine."""

    zone_id: str
    zone_name: str
    zone_type: str
    severity: str
    camera_id: str
    track_id: int
    class_name: str
    message: str
    timestamp: float = field(default_factory=time.time)
    centroid: list[int] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "type": "zone_alert",
            "zone_id": self.zone_id,
            "zone_name": self.zone_name,
            "zone_type": self.zone_type,
            "severity": self.severity,
            "camera_id": self.camera_id,
            "track_id": self.track_id,
            "class_name": self.class_name,
            "message": self.message,
            "timestamp": self.timestamp,
            "centroid": self.centroid,
        }


class VirtualFenceEngine:
    """
    Checks tracked object positions against defined virtual fence zones.

    Usage:
        engine = VirtualFenceEngine()
        engine.add_zone(FenceZone(...))
        alerts = engine.check(detections, camera_id="cam-01")
    """

    def __init__(self):
        self.zones: list[FenceZone] = []

        # Dwell tracking: {(zone_id, track_id): first_seen_timestamp}
        self._dwell_timers: dict[tuple[str, int], float] = {}

        # Previous positions for tripwire crossing: {track_id: (cx, cy)}
        self._prev_positions: dict[int, tuple[int, int]] = {}

        # Cooldown to prevent duplicate alerts: {(zone_id, track_id): last_alert_time}
        self._alert_cooldowns: dict[tuple[str, int], float] = {}
        self.cooldown_seconds: float = 5.0  # Min seconds between repeated alerts

    def add_zone(self, zone: FenceZone):
        """Register a new virtual fence zone."""
        self.zones.append(zone)
        print(f"[VirtualFence] Added zone: {zone.name} ({zone.zone_type.value})")

    def remove_zone(self, zone_id: str):
        """Remove a zone by ID."""
        self.zones = [z for z in self.zones if z.id != zone_id]

    def clear_zones(self):
        """Remove all zones."""
        self.zones.clear()
        self._dwell_timers.clear()

    def load_zones(self, zones_data: list[dict]):
        """Load zones from a list of dicts (e.g., from backend API)."""
        self.clear_zones()
        for z in zones_data:
            zone = FenceZone(
                id=z["id"],
                name=z["name"],
                camera_id=z["camera_id"],
                zone_type=ZoneType(z["zone_type"]),
                severity=AlertSeverity(z.get("severity", "high")),
                enabled=z.get("enabled", True),
                polygon_points=z.get("polygon_points", []),
                line_points=z.get("line_points", []),
                direction=z.get("direction"),
                dwell_threshold=z.get("dwell_threshold", 10.0),
                color=z.get("color", "#ef4444"),
            )
            self.add_zone(zone)

    def check(self, detections: list, camera_id: str) -> list[FenceAlert]:
        """
        Check all detections against all enabled zones for this camera.

        Args:
            detections: List of Detection objects from the detector
            camera_id: Camera identifier to filter zones

        Returns:
            List of FenceAlert objects for any triggered zones
        """
        alerts: list[FenceAlert] = []
        now = time.time()

        # Filter zones for this camera
        camera_zones = [
            z for z in self.zones if z.camera_id == camera_id and z.enabled
        ]

        if not camera_zones:
            # Update previous positions even if no zones
            for det in detections:
                self._prev_positions[det.track_id] = tuple(det.centroid)
            return alerts

        for det in detections:
            point = Point(det.centroid[0], det.centroid[1])
            prev_pos = self._prev_positions.get(det.track_id)

            for zone in camera_zones:
                cooldown_key = (zone.id, det.track_id)

                # Check cooldown
                last_alert = self._alert_cooldowns.get(cooldown_key, 0)
                if now - last_alert < self.cooldown_seconds:
                    continue

                alert = None

                if zone.zone_type == ZoneType.INTRUSION:
                    alert = self._check_intrusion(zone, det, point, now)

                elif zone.zone_type == ZoneType.TRIPWIRE:
                    alert = self._check_tripwire(zone, det, point, prev_pos, now)

                elif zone.zone_type == ZoneType.DIRECTIONAL_TRIPWIRE:
                    alert = self._check_directional_tripwire(
                        zone, det, point, prev_pos, now
                    )

                elif zone.zone_type == ZoneType.DWELL:
                    alert = self._check_dwell(zone, det, point, now)

                if alert:
                    alerts.append(alert)
                    self._alert_cooldowns[cooldown_key] = now

            # Update previous position
            self._prev_positions[det.track_id] = tuple(det.centroid)

        # Clean up stale dwell timers and previous positions
        active_track_ids = {d.track_id for d in detections}
        stale_keys = [
            k for k in self._dwell_timers if k[1] not in active_track_ids
        ]
        for k in stale_keys:
            del self._dwell_timers[k]

        stale_positions = [
            tid for tid in self._prev_positions if tid not in active_track_ids
        ]
        for tid in stale_positions:
            del self._prev_positions[tid]

        return alerts

    def _check_intrusion(
        self, zone: FenceZone, det, point: Point, now: float
    ) -> Optional[FenceAlert]:
        """Check if object centroid is inside the intrusion zone polygon."""
        polygon = zone.get_polygon()
        if polygon and polygon.contains(point):
            return FenceAlert(
                zone_id=zone.id,
                zone_name=zone.name,
                zone_type=zone.zone_type.value,
                severity=zone.severity.value,
                camera_id=zone.camera_id,
                track_id=det.track_id,
                class_name=det.class_name,
                message=f"⚠️ {det.class_name} #{det.track_id} entered zone '{zone.name}'",
                timestamp=now,
                centroid=det.centroid,
            )
        return None

    def _check_tripwire(
        self, zone: FenceZone, det, point: Point, prev_pos, now: float
    ) -> Optional[FenceAlert]:
        """Check if object track crossed the tripwire line between frames."""
        if prev_pos is None:
            return None

        line = zone.get_line()
        if line is None:
            return None

        # Create a line segment from previous position to current position
        movement = LineString([prev_pos, (det.centroid[0], det.centroid[1])])

        if movement.intersects(line):
            return FenceAlert(
                zone_id=zone.id,
                zone_name=zone.name,
                zone_type=zone.zone_type.value,
                severity=zone.severity.value,
                camera_id=zone.camera_id,
                track_id=det.track_id,
                class_name=det.class_name,
                message=f"🚧 {det.class_name} #{det.track_id} crossed tripwire '{zone.name}'",
                timestamp=now,
                centroid=det.centroid,
            )
        return None

    def _check_directional_tripwire(
        self, zone: FenceZone, det, point: Point, prev_pos, now: float
    ) -> Optional[FenceAlert]:
        """Check if object crossed tripwire in the specified direction."""
        if prev_pos is None:
            return None

        line = zone.get_line()
        if line is None:
            return None

        movement = LineString([prev_pos, (det.centroid[0], det.centroid[1])])

        if movement.intersects(line):
            # Determine crossing direction using cross product
            lp = list(line.coords)
            line_dx = lp[1][0] - lp[0][0]
            line_dy = lp[1][1] - lp[0][1]
            move_dx = det.centroid[0] - prev_pos[0]
            move_dy = det.centroid[1] - prev_pos[1]

            # Cross product determines which side the movement goes to
            cross = line_dx * move_dy - line_dy * move_dx

            crossing_dir = "left_to_right" if cross > 0 else "right_to_left"

            if zone.direction and crossing_dir == zone.direction:
                return FenceAlert(
                    zone_id=zone.id,
                    zone_name=zone.name,
                    zone_type=zone.zone_type.value,
                    severity=zone.severity.value,
                    camera_id=zone.camera_id,
                    track_id=det.track_id,
                    class_name=det.class_name,
                    message=(
                        f"➡️ {det.class_name} #{det.track_id} crossed "
                        f"'{zone.name}' ({crossing_dir})"
                    ),
                    timestamp=now,
                    centroid=det.centroid,
                )
        return None

    def _check_dwell(
        self, zone: FenceZone, det, point: Point, now: float
    ) -> Optional[FenceAlert]:
        """Check if object has been inside zone longer than the threshold."""
        polygon = zone.get_polygon()
        if polygon is None:
            return None

        key = (zone.id, det.track_id)

        if polygon.contains(point):
            if key not in self._dwell_timers:
                self._dwell_timers[key] = now
            else:
                elapsed = now - self._dwell_timers[key]
                if elapsed >= zone.dwell_threshold:
                    # Reset timer so alert can fire again after cooldown
                    self._dwell_timers[key] = now
                    return FenceAlert(
                        zone_id=zone.id,
                        zone_name=zone.name,
                        zone_type=zone.zone_type.value,
                        severity=zone.severity.value,
                        camera_id=zone.camera_id,
                        track_id=det.track_id,
                        class_name=det.class_name,
                        message=(
                            f"⏱️ {det.class_name} #{det.track_id} loitering in "
                            f"'{zone.name}' for {elapsed:.0f}s"
                        ),
                        timestamp=now,
                        centroid=det.centroid,
                    )
        else:
            # Object left the zone — remove dwell timer
            if key in self._dwell_timers:
                del self._dwell_timers[key]

        return None

    def get_zone_polygons_for_drawing(self, camera_id: str) -> list[dict]:
        """
        Get zone data formatted for drawing overlays on the annotated frame.

        Returns list of dicts with 'points', 'color', 'name', 'type' for each zone.
        """
        result = []
        for zone in self.zones:
            if zone.camera_id != camera_id or not zone.enabled:
                continue
            result.append(
                {
                    "id": zone.id,
                    "name": zone.name,
                    "type": zone.zone_type.value,
                    "color": zone.color,
                    "polygon_points": zone.polygon_points,
                    "line_points": zone.line_points,
                }
            )
        return result
